Name:           ros-indigo-libsensors-monitor
Version:        0.1.3
Release:        0%{?dist}
Summary:        ROS libsensors_monitor package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/libsensors_monitor
Source0:        %{name}-%{version}.tar.gz

Requires:       lm_sensors-devel
Requires:       ros-indigo-diagnostic-updater
Requires:       ros-indigo-roscpp
BuildRequires:  lm_sensors-devel
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-diagnostic-updater
BuildRequires:  ros-indigo-roscpp

%description
A ROS node for using libsensors to provide diagnostics information about the
sensors on a computer system.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon Jun 29 2015 Mitchell Wills <mwills@wpi.edu> - 0.1.3-0
- Autogenerated by Bloom

* Tue Jan 06 2015 Mitchell Wills <mwills@wpi.edu> - 0.1.2-0
- Autogenerated by Bloom

